name: Feature branch workflow

on:
  push:
    branches-ignore:
      - main

env:  
  GO_VERSION: 1.23

jobs:
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  go-build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build
        run: make build

  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Test
        run: make test
          
  docker-build:
    uses: ./.github/workflows/docker.yml
    needs: ["go-lint", "go-build", "go-test"]
    permissions:
      id-token: write
      packages: write
      contents: read
    with:
      with-push: false
      image-architectures: linux/amd64